name: salsa_challenge_workspace
description: Challenge project for Salsa Tech.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

workspace:
  - salsa_challenge
  - packages/auth
  - packages/core
  - packages/database
  - packages/design_system
  - packages/home
  - packages/splash