name: salsa_challenge
description: Challenge project for Salsa Tech.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  clock: ^1.1.2
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  get_it: ^8.2.0
  go_router: ^16.2.0
  hive: ^2.2.3
  isar_flutter_libs: ^3.1.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  mobx: ^2.5.0
  path_provider: ^2.1.0

dev_dependencies:
  build_runner:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  fake_async: ^1.3.2
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  mobx_codegen: ^2.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
