name: core
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: 
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0