name: splash
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  auth:
    path: ../auth
  core: ^0.0.1
  design_system: ^0.0.1
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  gap: ^3.0.1
  logging: ^1.3.0
  mobx: ^2.5.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mobx_codegen: ^2.7.1
  mockito: ^5.4.6

flutter:
  uses-material-design: true