name: home
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  core:
    path: ../core
  design_system:
    path: ../design_system
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  gap: ^3.0.1
  logging: ^1.2.0
  mobx: ^2.5.0

dev_dependencies:
  build_runner: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mobx_codegen: ^2.7.1

flutter:
  uses-material-design: true