name: home
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  cached_network_image: ^3.4.1
  core:
    path: ../core
  database:
    path: ../database
  design_system:
    path: ../design_system
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  json_annotation: ^4.9.0
  logging: ^1.2.0
  mobx: ^2.5.0
  webview_flutter: ^4.13.0

dev_dependencies:
  build_runner: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  mobx_codegen: ^2.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true